### ISSUE TITLE
[Bug]: opik doesn't work with adk 1.32 or newer

### ISSUE THREAD

**Issue by rcleveng** [comet-ml/opik#6635]
### What component(s) are affected?

- [x] Opik Python SDK
- [ ] Opik Typescript SDK
- [ ] Opik Agent Optimizer SDK
- [ ] Opik UI
- [ ] Opik Server
- [ ] Documentation

### Opik version

- Opik version: 1.9.33 or any 2.x latest

### Describe the problem

Google ADK 1.32 removed tracer as a module level variable, opik uses it.

```
 AttributeError: module 'google.adk.agents.base_agent' has no attribute 'tracer'
  mock_enriched_auth_context = <lairo_auth.context.AuthContext object at 0x7f720cc16570>

      @pytest.mark.asyncio
      async def test_generate_memory_session_not_found(mock_enriched_auth_context):
          """Test 404 when thread_id not in session cache."""
  >       from main import generate_session_memory

  tests/test_main.py:193:
  _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
  main.py:251: in <module>
      adk_agent=create_root_agent(model=create_llm(settings.default_root_agent_model)),
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  agents/root_agent.py:242: in create_root_agent
      if (opik_tracer := create_opik_tracer(model)) is not None:
                         ^^^^^^^^^^^^^^^^^^^^^^^^^
  agents/root_agent.py:64: in create_opik_tracer
      _opik_tracer = OpikTracer(
  ../../.venv/lib/python3.14/site-packages/opik/integrations/adk/opik_tracer.py:64: in __init__
      self._init_internal_attributes()
  ../../.venv/lib/python3.14/site-packages/opik/integrations/adk/opik_tracer.py:75: in _init_internal_attributes
      patchers.patch_adk(
  ../../.venv/lib/python3.14/site-packages/opik/integrations/adk/patchers/patchers.py:23: in patch_adk
      _patch_adk_opentelemetry_tracers(
  _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

  distributed_headers = None

      def _patch_adk_opentelemetry_tracers(
          distributed_headers: Optional[DistributedTraceHeadersDict],
      ) -> None:
          no_op_opik_tracer = opik_adk_otel_tracer.OpikADKOtelTracer(
              distributed_headers=distributed_headers,
          )

          adk_telemetry.tracer.start_as_current_span = no_op_opik_tracer.start_as_current_span
          adk_telemetry.tracer.start_span = no_op_opik_tracer.start_span

  >       base_agent.tracer.start_as_current_span = no_op_opik_tracer.start_as_current_span
          ^^^^^^^^^^^^^^^^^
  E       AttributeError: module 'google.adk.agents.base_agent' has no attribute 'tracer'

  ../../.venv/lib/python3.14/site-packages/opik/integrations/adk/patchers/patchers.py:71: AttributeError
```

**Comment by alexkuzmik** [comment]
Hi @rcleveng! It should've been [fixed](https://github.com/comet-ml/opik/pull/6613/changes/bf77b86e4d0a1752e0ccfcd7e5fd6d55df030bf5) in 2.0.23, 2 days ago. Could you please double-check with the latest version?

**Comment by rcleveng** [comment]
Will do.  I have a block on any deps less than 7 days old to try to minimize supply chain attacks.  Thanks for already having a fix out!

**Comment by rcleveng** [comment]
That worked, thanks!
