### PR TITLE
[OPIK-7791] [QA] Proposed e2e specs from the 2.2.54 → 2.2.55 release exploration

### PR DESCRIPTION
**Pull request by CometActions**
> **Generated by the release QA side flow** (release exploration → test proposal).
> Nothing here has been reviewed by a human. It is a **draft**: please read the
> assertions before promoting it, and do not merge it on a green CI run alone.

## Details

Two behaviours that a QA exploration pass verified by hand on staging during the
**2.2.54 → 2.2.55** release, turned into permanent assertions.

**Written and run against the `2.2.55` release ref** (commit `07ef0c6`), which is
what the specs were verified on. They are based on `main` because that is where
they have to merge — `2.2.55` is a tag, not a branch — so `main` will have moved
on since. `2.2.55` is an ancestor of `main`, so the diff here is only these
commits.

Both candidates **extend an existing spec in `trace-explore`** rather than adding
a parallel one for the same capability, because in both cases the capability was
already nominally covered and the gap was in the seed matrix, not in the spec.

### 1. Reasoning tokens bill at their own rate — `traces.span-model-cost-tokens`

Extends `tests/trace-explore/span-cost-resolution.spec.ts` and its fixture.

[PR 7777](https://github.com/comet-ml/opik/pull/7777) changed
`SpanCostCalculator.textGenerationCost` so reasoning/thinking tokens bill at
`output_cost_per_reasoning_token` and are subtracted from the standard-output
bucket instead of being billed at both rates. `span-cost-resolution.spec.ts`
nominally covers this capability, but **all five of its seed models carry a cache
price**, so they route to `textGenerationWithCacheCost*` — the function 7777
changed never executed in it.

The fixture gains five vectors on **`perplexity/sonar-deep-research`**. That model
is not an arbitrary pick: it is the only entry in the shipped price table that can
observe the change at all. The vector needs a model that publishes a reasoning
rate, has **no** cache price, belongs to a provider in
`CostService.PROVIDERS_MAPPING`, **and** whose reasoning rate differs from its
output rate — otherwise the split is arithmetically invisible and the spec would
pass with the feature removed. Of the 72 entries publishing
`output_cost_per_reasoning_token`, exactly one satisfies all four. (The release
report's own suggested models — `gemini/gemini-omni-flash-preview` and
`dashscope/qwen-turbo` — were checked on staging and **cannot** detect this: the
first prices identically with and without reasoning tokens, the second prices
`null` because `dashscope` is unmapped.)

The new test asserts, at 1M prompt + 1M completion tokens:

| Vector | Reasoning tokens | Expected |
|---|---|---|
| no reasoning key (control) | — | $10.00 |
| `original_usage.completion_tokens_details.reasoning_tokens` | 400,000 | $8.00 |
| bare OTel `completion_tokens_details.reasoning_tokens` | 400,000 | $8.00 |
| over-report (clamps to `completion_tokens`) | 1,500,000 | $5.00 |
| negative (clamps to 0) | −100,000 | $10.00 |

…plus the relationships that encode the behaviour independently of the table:
the reasoning vector costs **strictly less** than the identical control (this is
what an absolute assertion alone could not tell apart from the price table
moving), the OTel key resolves the same price as the SDK key, and both clamps
hold.

**One thing worth a reviewer's attention.** The bare-OTel-key vector cannot be
seeded through the SDK bridge. The Python SDK normalises usage keys, re-emitting
`completion_tokens_details.reasoning_tokens` under the `original_usage.` prefix
(verified against `validation_helpers.validate_and_parse_usage`), so a seed aimed
at the backend's **fallback** key would silently arrive on the **primary** one and
pass for the wrong reason. That vector is therefore written straight to
`POST /v1/private/spans` via `backendClient.createSpan`, which is also how such a
span really arrives in production — from OTel ingestion, not from the SDK. The
fixture documents this; the alternative was a vector that looked like fallback
coverage and was not.

### 2. Deleting a trace cascades to its spans — `traces.delete-traces-api`, `traces.delete-traces`

Extends `tests/trace-explore/trace-delete.spec.ts`.

[PR 8201](https://github.com/comet-ml/opik/pull/8201) reorders the deletion-events
capture ahead of the lightweight delete and wraps both the trace delete and the
`SpanService` cascade in `Mono.defer`. The reorder is unconditional and ships on
every deployment regardless of the capture flags. Both existing tests in that file
seed **span-less** traces, so the cascade ran only in fixture teardowns, where
nothing read the result.

The new test seeds two 5-span traces and a 4-span control, with the spans **chained**
(each parented to the previous) so the cascade has depth to lose, and a feedback
score and a comment on both the trace and its deepest span so the delete has
dependent rows at both levels. It then deletes through **both** entry points —
`DELETE /v1/private/traces/{id}` and the Logs table's bulk delete — because a
cascade that broke on one would still look healthy on the other.

Two details that are the point of the test rather than incidental:

- **The project-wide cross-check.** `GET /spans?trace_id=<deleted>` answering
  "0 spans" is *not* evidence the cascade ran: a filter on a trace that no longer
  exists matches nothing either way, so a delete that removed the trace and
  orphaned every span produces that same zero. The test names the surviving set
  project-wide instead.
- **The bystander.** The control trace is never touched, and is asserted intact in
  substance — its spans, its trace-level score, its trace and span comments — not
  merely present, since an over-reaching delete could take the dependent rows and
  leave the row that renders in the table.

The UI half asserts the row leaves the table **without a reload**.

### What was deliberately not written

- **A permanent provider error in the automation log** (`online-evaluation.automation-logs`,
  [PR 8169](https://github.com/comet-ml/opik/pull/8169)) — **dropped, unrunnable
  here.** The candidate's flow needs a `custom-llm` provider pointed at the
  estate's own mock gateway (`services/mock-token-auth`) to force a 401. That mock
  binds to the test runner, and this run targeted a **cloud** deployment
  (`staging.dev.comet.com`) whose backend cannot reach it — the estate already
  codifies exactly this in `core/mock-auth.ts`, where `mockAuthSkipReason()`
  refuses outright for any non-`oss` deployment rather than even probing. (The
  runner confirms it: its only addresses are private, `10.4.104.165` and
  `172.17.0.1`, behind NAT.) The alternative — pointing a provider at a real
  third-party endpoint that 401s — would put an external network dependency inside
  an e2e assertion, which is the thing the mock gateway exists to avoid. Rather
  than ship a spec that could only ever `.skip` on the environment it was proposed
  from, it is left out and `online-evaluation.automation-logs` stays
  `covered: false`. It is worth writing against a local OSS backend, where the
  mock is reachable.

  Worth flagging separately: the exploration report this came from records item 3's
  verdict as *pending*, and its own environment notes say a read at +3 min could
  not tell the permanent and retryable cases apart. So this candidate was marked
  `verified_on_staging: true` without a recorded verification.
- **A transient provider error being retried** — not automatable at e2e level.
  `onlineScoring.pendingMessageDuration` defaults to 10m, so no e2e can wait for a
  redelivery. Belongs in the backend's own tests.
- **Deletion-events rows in `deletion_events_local`** — needs a deployment flag
  change and direct ClickHouse access, both out of reach from the e2e estate.
- **An attachment on a deleted trace.** The cascade test covers comments and
  feedback scores on trace and span, not attachments. The exploration did not
  exercise that either.

### Known trade-off

The reasoning-token amounts hardcode the shipped price table's rates, which are
synced daily from LiteLLM. That coupling is real, but it is the estate's existing
trade-off — `span-cost-resolution.spec.ts` already hardcodes table prices — not a
new one introduced here. The relational assertions are there partly so a table
move produces a legible failure rather than a mysterious one.

## Change checklist

- [x] Specs live in the area's own `spec_dir` (`trace-explore`) and extend the
      existing spec for the capability instead of duplicating it
- [x] Imports come from `@e2e/fixtures`; interaction goes through `@e2e/pom`
      (`LogsPage`) — no raw selectors in the specs
- [x] Seeding is through the SDK bridge, except the one vector the SDK provably
      cannot express, which is documented at its call site
- [x] Teardown is owned by fixtures, not by the test body
- [x] Every `@area:`/`@cap:` value already existed in `coverage/taxonomy.yaml`;
      no new keys invented, and no capability flipped to `covered: true` on the
      strength of a surface it does not exercise
- [x] `taxonomy.yaml` notes updated to state what is now asserted. **The area's
      `specs:` list is deliberately untouched** — the nightly reconcile job
      derives it from the `@area:` tag, and hand-editing it is what made this file
      the most-conflicted in the queue
- [x] No fixed sleeps; async state is awaited with `expect.poll`
- [x] No `.skip`, and no spec included that was not run green
- [x] Only spec, fixture, POM-support and taxonomy files committed — no
      exploration report, candidate list, screenshots or run artifacts

## Issues

OPIK-7791

Related product changes the specs are aimed at: #7777 (reasoning-token cost),
#8201 (trace delete / span cascade). Candidate dropped from this PR: #8169
(provider-error automation logs) — see *What was deliberately not written*.

## Testing

Run against `$OPIK_BASE_URL = https://staging.dev.comet.com/opik` (serving
`2.2.55`), `OPIK_DEPLOYMENT=cloud`, workspace `opik-testing`, from the `2.2.55`
ref with these changes applied.

```
npx playwright test tests/trace-explore/span-cost-resolution.spec.ts --reporter=line
  3 passed (22.3s)

npx playwright test tests/trace-explore/trace-delete.spec.ts --reporter=line
  3 passed (32.4s)
```

| Spec | Result |
|---|---|
| `span-cost-resolution.spec.ts` — reasoning tokens bill at the reasoning rate (new) | **passed** |
| `span-cost-resolution.spec.ts` — id normalisation, widened to the new seeds (existing) | **passed** |
| `span-cost-resolution.spec.ts` — trace panel renders each resolved cost, now over 8 priced spans (existing) | **passed** |
| `trace-delete.spec.ts` — delete cascades to nested spans, API + Logs (new) | **passed** |
| `trace-delete.spec.ts` — the two existing delete tests | **passed** |

Also run, since this change touches shared `core/` helpers rather than only spec
files:

```
python3 tests_end_to_end/coverage/tag_lint.py \
  --taxonomy tests_end_to_end/coverage/taxonomy.yaml --estate tests_end_to_end
  tag-lint: 72 specs checked, 1 exempt, 0 problem(s)

npx playwright test tests/trace-explore/ --reporter=line     # full feature directory
  4 flaky
  22 passed (8.3m)
```

The whole feature directory is green, with **4 flaky and 0 failed**. All four
flakes are **pre-existing tests, not the new ones** — `thread-logging-smoke`,
`trace-attachments`, `trace-explore-smoke`, and the *existing* bulk-delete test at
`trace-delete.spec.ts:93` (the new cascade test is at `:185` and passed first
time, as did the new reasoning test). All four failed with the same
`PythonSdkBridgeError: POST /traces aborted after 30000ms` and passed on retry,
alongside a run-long stream of `HTTP 429 … for 'search_traces'` — i.e. shared
staging throttling a 26-test parallel load, not a code fault. Worth knowing that
this directory cannot currently be run at full parallelism against shared
staging without retries.

**One honest failure along the way, and what it was.** The cascade test failed on
its first run asserting a seeded trace comment could be read back. The cause was
the spec, not the app: `CommentServiceImpl.create` mints its own comment id and
ignores any the caller sends, returning the real one in `Location`. The helper now
reads the id from the header (the same way `createAutomationRule` does) and the
test passes. No app defect was found by either spec on its first green run.

**A pre-existing issue noticed but not touched.** `npx tsc --noEmit` fails at this
ref before any of these changes, with `TS5102: Option 'baseUrl' has been removed`
— the pinned `typescript: ^7.0.2` no longer accepts the `baseUrl` in
`tests_end_to_end/e2e/tsconfig.json`. `main` has the same tsconfig. Typechecking
here was done with an equivalent config that expresses the path alias without
`baseUrl` (not committed); it reports only two pre-existing duplicate
`deleteDashboard` identifiers in `core/backend/client.ts:899,1554`, both untouched
by this change. Separately, `tests/ai-providers/token-auth-refetch.spec.ts` fails
to load at this ref (`test.describe() in a configuration file`), also pre-existing
and unrelated. Both look worth a follow-up ticket; neither is in scope here.

## Documentation

No documentation change is needed. This adds test coverage only — no user-facing
behaviour, API, SDK surface or configuration changes. The `coverage/taxonomy.yaml`
notes, which are the estate's own record of what each capability's coverage
actually claims, are updated in this PR.

### CODE REVIEW

**Comment by CometActions** [comment]
## 🔍 Generated-test review

# PR #8226 — [OPIK-7791] [QA] Proposed e2e specs from the 2.2.54 → 2.2.55 release exploration

CometActions · draft: yes · 8 files, 0 new spec files, 2 new tests in 2 existing specs

**VERDICT: ready with notes** — a person should flip it to ready; I have not and will not.

Two fixes applied and pushed (`be5547a045`). No blockers in this PR. The one blocking-shaped
problem I found is **the estate's**, not this PR's, and belongs in its own PR.

Specs run against the local Opik built from this PR's head: **6/6 passed**, before and after
my fixes.

---

## Blockers (0 in this PR)

None. Placement, tag honesty, fixture reuse, teardown and namespacing all check out — details
under Notes.

## Estate blocker — the `tsc` gate is vacuous, and is hiding a real error (own PR)

This is not caused by #8226 and must not be fixed inside it, but it is the most important thing
I found and it undermines every generated PR's review.

`tests_end_to_end/e2e/package.json` pins `"typescript": "^7.0.2"`, and TypeScript 7 **removed**
`baseUrl`, which `tsconfig.json:13` still sets:

```
tsconfig.json(13,5): error TS5102: Option 'baseUrl' has been removed.
```

TS5102 is a **config-level** error, so tsc exits before type-checking a single file. The gate has
not checked any TypeScript since TS 7 landed — it only reports that the config is stale. Neither
file is touched by this PR and both are byte-identical to `origin/main`, so this fails on main too.

I reconstructed a working config (drop `baseUrl`, pin `typeRoots: ["./node_modules/@types"]` — the
default typeRoots resolution keys off `baseUrl`, so removing it alone loses `@types/node` and
produces ~90 spurious errors) and type-checked the whole tree. Result: **exactly two errors, both
pre-existing, neither from this PR.**

```
core/backend/client.ts(899,11):  error TS2300: Duplicate identifier 'deleteDashboard'.
core/backend/client.ts(1554,11): error TS2300: Duplicate identifier 'deleteDashboard'.
```

Present on `origin/main` too (lines 936 and 1591). This is the append-only-shared-file hazard
landing for real: two PRs each appended `deleteDashboard` to `client.ts`, both merged without a
textual conflict, and the broken gate never said a word.

**This PR's own TypeScript type-checks clean.** That is the useful half of the finding.

Fix belongs in a separate PR: remove `baseUrl`, add `typeRoots`, delete one of the two
`deleteDashboard` definitions. I can open it — say the word. I did not fold it in here because
it means editing merged code owned by two other PRs, which is outside this review's scope.

## Fixed in this PR (pushed as `be5547a045`)

**1. The panel cost assertions had stopped discriminating** —
`tests/trace-explore/span-cost-resolution.spec.ts:279`

The loop `selectSpan(name)` → assert model chip → assert cost is verbatim from main, and on main
it was sound: three priced spans, three distinct models, three distinct costs. This PR adds five
reasoning vectors **all on `perplexity/sonar-deep-research`**, of which two pairs share an expected
amount ($8 for `reasoning-sdk-key`/`reasoning-otel-key`, $10 for `reasoning-absent`/`reasoning-negative`)
— and those two $8 vectors are *adjacent* in iteration order.

`TracePanelPage.selectSpan` only waits for *some* span to appear in the URL, not for the selection
to change. So an iteration where the click didn't land would still see the previous span's model
(identical) and cost (identical) and pass. A test that cannot fail.

Fixed by pinning each iteration to the span id actually in the URL, read from the backend:

```ts
await expect
  .poll(() => new URL(page.url()).searchParams.get('span'), {
    message: `the panel must be showing '${seed.name}' itself, not whichever span was selected before it`,
  })
  .toBe(byName.get(seed.name)!.id);
```

Verified it can fail: pointed at a wrong id, the test goes red with that message. Kept spec-local
rather than changing `selectSpan`, whose blast radius is every trace-panel spec.

**2. Dependent rows were seeded to be cascaded and then never asserted** —
`tests/trace-explore/trace-delete.spec.ts:303,345`

The cascade test attaches a feedback score and a comment to each doomed trace and its deepest span,
commenting that this is "so the delete has dependent rows at both levels to clean up". It then
asserted only that spans and traces vanished — the comments were seeded and forgotten, so the
seeding proved nothing.

Added assertions that the trace-level and span-level comments are gone after **both** the REST
delete and the Logs bulk delete. **The product does cascade them** — this passes, so it is real
coverage, not a weakened claim. (The pre-delete step already asserts both comments are readable,
so the new assertions have a proven live starting state.)

## Notes (4)

**1. The span cascade has no capability key of its own, and the PR did the right thing.**
The new test is tagged `@cap:traces.delete-traces-api` + `@cap:traces.delete-traces` and genuinely
exercises both surfaces, so the dual tag is honest. But "deleting a trace takes its spans with it"
is not itself a taxonomy key; the PR folded it into both capabilities' `note:` fields rather than
inventing one. That is correct per the estate's rules and I have not changed it. **Your call**
whether the cascade deserves its own capability — I will not invent one.

**2. `listSpanRefs` is a near-duplicate of `listSpanCosts`** — `core/backend/client.ts:1955`.
Same endpoint (`getSpansByProject`), different projection: `listSpanCosts` returns
model/provider/cost and requires `traceId`; the new `listSpanRefs` returns `traceId`/`parentSpanId`
and makes `traceId` optional. The optional-`traceId` form is the whole point of the cascade
assertion and is well argued in its docblock, so this is defensible — but one method with a wider
return type would have done. Not fixed: merging them touches existing `listSpanCosts` callers.

**3. The branch is 3 commits behind `main`, one of which touches `client.ts`.**
`9d9b779c40` (#8202) is on main and not in this branch. Git reports MERGEABLE / 0 conflicts, and I
checked the semantic case that git will not: all seven symbols this PR adds to shared files
(`SpanRef`, `listSpanRefs`, `addTraceFeedbackScore`, `addSpanFeedbackScore`, `addComment`,
`getTraceComment`, `getSpanComment`) appear **zero** times on `origin/main`, so the append-only
merge will not produce another duplicate-identifier collision like `deleteDashboard`. I did not
merge main in, because `e05a60c4b2` (#8214) bumps the e2e dependency group and would desync the
installed `node_modules` from the tree I just ran the specs against.

**4. Cosmetic: the `span-model-cost-tokens` taxonomy note reads awkwardly** —
"…as a fallback for the original_usage. one, and both clamps". The `original_usage.` trailing dot
is the key prefix, not a sentence end. Left alone; it parses fine and #8218 only constrained braces.

## What holds up well

Worth saying plainly, because these are the things this review exists to catch and the PR got them
right:

- **The destructive test has a real bystander.** The cascade test seeds an untouched 4-span control
  and asserts survival **project-wide and id-precise** — the surviving span set is named, the
  remaining trace list is compared to `[control.id]`, and the control's own score and comments are
  checked. The spec's own comment explains why a `trace_id`-filtered zero would have proved nothing.
  This is exactly the sharper question the rules ask for.
- **The seed is asserted before anything is deleted**, so "it is gone" cannot pass over state that
  never landed.
- **The `otel-rest` writer is justified, not a shortcut.** The Python SDK rewrites bare OTel usage
  keys onto the `original_usage.` prefix, so a bridge-seeded fallback vector would silently test the
  primary key and pass for the wrong reason. Writing that one span straight to the REST API is the
  faithful stand-in for OTel ingestion, and it is documented in three places.
- Placement correct (`traces.spec_dir: trace-explore`), both specs already in the area's `specs:`
  list, all `@cap:` keys real, all tags string literals, tier `@t2-cuj` appropriate (no LLM spend,
  ~30s total), no `waitForTimeout`, no `.skip`/`.fixme`, teardown in the fixture, entities namespaced
  to the `cuj-` timestamp contract (global teardown swept clean on both runs).

## Bot comments

`bot-comments.json` is empty (`[]`) — no bot review comments on this PR. Nothing to triage.

| # | Finding | Verdict | Disposition |
|---|---------|---------|-------------|
| — | none posted | — | — |

## Conflicts

`conflicts.txt` is empty and `restack-report.json` reports 0 inherited commits and 0 conflicts.
Nothing to resolve; no finding here is moot.

## Spec run

Local Opik at `http://localhost:5173`, `OPIK_DEPLOYMENT=oss`, workspace `default`, built from this
PR's head.

```
npx playwright test tests/trace-explore/span-cost-resolution.spec.ts \
                    tests/trace-explore/trace-delete.spec.ts --reporter=list --retries=0
→ 6 passed (24.2s)      [after my fixes]
→ 6 passed (29.7s)      [before, as the PR stood]
```

No failures to diagnose, and no product defects found.

## Estate gates

| Gate | Result | Note |
|---|---|---|
| tag_lint | **PASS** | 72 specs checked, 1 exempt, 0 problems |
| tsc | **FAIL** | pre-existing and estate-wide, not this PR — TS5102 on `tsconfig.json:13`; see above. This PR's own code type-checks clean under a corrected config. |
| playwright --list | **PASS** | 6 tests in 2 files |

## What I could not verify

- **The fixture's "only one model can observe this" claim.** `model-cost-spans.fixture.ts:92`
  states that of 72 price-table entries publishing a reasoning rate, exactly one satisfies all four
  constraints. I did not enumerate the shipped price table. The vector demonstrably works — the
  spec's discriminating assertion (`reasoning-sdk-key` < `reasoning-absent`) passes, which is what
  matters — but "exactly one" is the generator's arithmetic, unchecked.
- **The suite on a tree merged with current `main`.** I verified clean mergeability and the absence
  of symbol collisions, but did not run the specs against a merged tree, because #8214's dependency
  bump would invalidate the installed `node_modules`.
- **`reasoning-negative` distinguishes "clamped to zero" from "key ignored".** It cannot — both
  price at $10. The spec's own comment is candid about this and the behaviour is the same either
  way, so it is honest rather than wrong.

## Ready?

Yes — with the caveat that the `tsc` gate will stay red until the separate estate PR lands, and a
reader should not mistake that red for this PR's doing. **I have not marked it ready and have not
merged it.** A person should flip the draft flag.

### ✅ Post-fix verification

The specs this PR touches were re-run against staging after the fixes were pushed: **6 passed**.

---
_[review_generated_tests.yml](https://github.com/comet-ml/comet-automation-tests/actions/runs/34337096880) ·
this PR stays a draft — a human decides when it is ready._


[OPIK-7791]: https://comet-ml.atlassian.net/browse/OPIK-7791?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Review by AndreiCautisanu — APPROVED** [review]
